### ISSUE TITLE
Using proxied cache while offline

### ISSUE THREAD

**Issue by Boomaa23** [dzikoysk/reposilite#537] opened 2021-07-16 10:05 UTC
I would like to do the following.
1. Cache a copy of a proxied artifact going to a maven project (connected to internet)
2. Send that cached artifact to a different computer with the same maven project
    (on the same network, but now not connected to the internet)

Does reposilite support this or can it be a feature in the future?

I tried testing this (v2.9.23) but it just failed to resolve the proxied servers and didn't look for the cached copies of the artifacts. Thanks.

**Comment by dzikoysk** [comment] 2021-07-16 13:21
Reposilite searches for artifacts locally and in case of a missing one it requests proxied repositories. Do you have enabled proxied artifacts storage? 

* https://github.com/dzikoysk/reposilite/blob/8e44bd801fba64b6c0ce6a4558508788842024e5/reposilite-backend/src/test/workspace/reposilite.cdn#L61

Remember that you have to request all of the required files before you'll go offline.

**Comment by Boomaa23** [comment] 2021-07-16 23:20
Yes I have that set to true and requested everything once online first. I can see a copy of everything in the releases repo as well.

Some steps to recreate:
1. Clone https://github.com/Team5818/CheeseWrangler-2020
2. Change the repo in build.gradle.kts to point to localhost
3. Start a reposilite jar
4. Run gradlew downloadAll
5. Disconnect network
6. Clear gradle cache (~/.gradle/)
7. Run gradlew downloadAll

And on step 7 it spits out errors about how it can't resolve the servers, hence my issue.

**Comment by dzikoysk** [comment] 2021-07-16 23:43
Hmm... Related to #535 I'm currently not able to reproduce it and play with it unfortunately. I guess that Gradle requests some files that are not cached by Reposilite (some metadata files maybe) and then it of course may fail. Because of the fact that Reposilite has been rewritten on 3.0 branch, I probably wouldn't be able to port such a fix to 2.x anyway. I'll keep this open to remember about it during the tests of 3.0 and I'll see if there is something that could be improved to make it possible :)

**Comment by dzikoysk** [comment] 2021-08-06 16:02
Addressed in #544

**Closed by dzikoysk** 2021-08-06 16:02 UTC
Labels: enhancement, question, investigation
