### ISSUE TITLE
 Incorrectly Classifier Jar File Downloaded from Mirror Repository

### ISSUE THREAD

**Issue by MiniDay** [dzikoysk/reposilite#2057] opened 2024-03-01 07:36 UTC
### What happened?

I have two Reposilite instances, one for my personal use and one for my team.

In my personal Reposilite, I published a project that uses `com.github.johnrengelman.shadow` to package third-party dependencies into the jar file.

The project's Gradle configuration is roughly as follows:

```kotlin
apply {
    plugin("java-library")
    plugin("maven-publish")
    plugin("com.github.johnrengelman.shadow")
}

repositories {
    // ...
}

dependencies {
    // ...
}

tasks {
    jar {
        archiveClassifier = "dev"
    }
    shadowJar {
        archiveClassifier = ""
        // relocate ...
    }
}

publishing {
    publications {
        create<MavenPublication>("mavenJava") {
            from(components["java"])
        }
    }
    repositories {
        // ...
    }
}
```

Normally, when I need to use the complete code of this project (including the third-party dependencies packaged into the jar file and the relocated code information), I only need to use `compileOnly("cn.hamster3.mc.plugin:core-bukkit:1.2.2")`.

When I only need a small part of this code information (excluding the third-party dependencies packaged into the jar file and the relocated code information), I need to use `compileOnly("cn.hamster3.mc.plugin:core-bukkit:1.2.2:dev")`.

I have always used it this way, and it works very well.

However, when I write the team's project, I added a mirror of my personal repository to the team's Maven repository, and then introduced the team's Maven repository address in the project.

Finally, I added the dependency information `compileOnly("cn.hamster3.mc.plugin:core-bukkit:1.2.2")` to the project. It is obvious that at this time I want to depend on the complete jar file, including the relocated third-party dependency code.

However, the final download from the team's Maven repository is the `-dev` version, without the relocated third-party code, which causes my project to fail to compile.

By checking the log, I found that the team's Maven repository downloaded the `-dev` version file from my personal repository and sent it to my computer.

Finally, I tested it repeatedly for the same `compileOnly("cn.hamster3.mc.plugin:core-bukkit:1.2.2")` dependency information.

When the repositories are replaced with my personal repository address, the complete jar file can be downloaded.

However, when the repositories are replaced with the team's repository address, only the `-dev` version file can be downloaded.

Both repositories use Reposilite version 3.5.6. If you need additional information, please let me know.

**This issue was written in Chinese and translated into English by Google AI. If there are any inappropriate or unclear content, please forgive me.**

### Reposilite version

3.x

**Comment by dzikoysk** [comment] 2024-03-01 21:55
Hey @MiniDay :)

You've said that this repository is mirrored, so I think we have an issue with mirroring rules. To properly resolve classifiers, Gradle requires `.module` file, but in older versions of Reposilite it wasn't added to the default list of allowed extensions. Could you check if you have this added on your side?

![obraz](https://github.com/dzikoysk/reposilite/assets/4235722/8b2668d9-ce8f-4a9c-b149-bd4b1a315038)

**Comment by MiniDay** [comment] 2024-03-02 04:42
Thank you for your reply @dzikoysk 

Yes, I did not add `.module` to the allowed extensions list before. However, I just tried adding it, but the problem still persists.

**Comment by dzikoysk** [comment] 2024-03-02 13:28
If all files are allowed to be transferred, then this is unlikely an issue with Reposilite. It might be a good idea to enable debug mode in the console with this command:

```
level debug
```

and request this artifact once again. You should see some more detailed data about each request and how it was resolved by Reposilite. We're not modifying any build files, so if all requests are properly resolved, then this is related to build misconfiguration.

**Comment by MiniDay** [comment] 2024-03-06 02:31
I tried to open the debug log as you said, and here are some relevant information from when I built the project.

```log
02:04:06.421 DEBUG | HEAD /public/cn/hamster3/mc/plugin/core-bukkit/1.2.2/core-bukkit-1.2.2.pom from 183.***.***.***
02:04:06.422 DEBUG | ACCESS | Unauthorized attempt of access (token: null) to cn/hamster3/mc/plugin/core-bukkit/1.2.2/core-bukkit-1.2.2.pom from public
02:04:06.462 DEBUG | HEAD /public/cn/hamster3/mc/plugin/core-bukkit/1.2.2/core-bukkit-1.2.2.pom from 183.***.***.***
02:04:06.462 DEBUG | Gav 'cn/hamster3/mc/plugin/core-bukkit/1.2.2/core-bukkit-1.2.2.pom' found in 'public' repository
02:04:06.506 DEBUG | GET /public/cn/hamster3/mc/plugin/core-bukkit/1.2.2/core-bukkit-1.2.2.pom.sha1 from 183.***.***.***
02:04:06.507 DEBUG | Gav 'cn/hamster3/mc/plugin/core-bukkit/1.2.2/core-bukkit-1.2.2.pom.sha1' found in 'public' repository
02:04:06.553 DEBUG | HEAD /public/cn/hamster3/mc/plugin/core-bukkit/1.2.2/core-bukkit-1.2.2.module from 183.***.***.***
02:04:06.554 DEBUG | Gav 'cn/hamster3/mc/plugin/core-bukkit/1.2.2/core-bukkit-1.2.2.module' found in 'public' repository
02:04:06.595 DEBUG | GET /public/cn/hamster3/mc/plugin/core-bukkit/1.2.2/core-bukkit-1.2.2.module.sha1 from 183.***.***.***
02:04:06.596 DEBUG | Gav 'cn/hamster3/mc/plugin/core-bukkit/1.2.2/core-bukkit-1.2.2.module.sha1' found in 'public' repository
02:04:13.497 DEBUG | HEAD /public/cn/hamster3/mc/plugin/core-bukkit/1.2.2/core-bukkit-1.2.2-dev.jar from 183.***.***.***
02:04:13.497 DEBUG | ACCESS | Unauthorized attempt of access (token: null) to cn/hamster3/mc/plugin/core-bukkit/1.2.2/core-bukkit-1.2.2-dev.jar from public
02:04:13.584 DEBUG | HEAD /public/cn/hamster3/mc/plugin/core-bukkit/1.2.2/core-bukkit-1.2.2-dev.jar from 183.***.***.***
02:04:14.251 DEBUG | HttpRemoteClient | https://maven.airgame.net/maven-airgame/cn/hamster3/mc/plugin/core-bukkit/1.2.2/core-bukkit-1.2.2-dev.jar responded with 200 (Content-Type: application/java-archive)
02:04:14.252 DEBUG | Cannot find 'cn/hamster3/mc/plugin/core-bukkit/1.2.2/core-bukkit-1.2.2-dev.jar' in 'public' repository, requesting proxied repositories
02:04:14.422 DEBUG | HttpRemoteClient | https://maven.airgame.net/maven-airgame/cn/hamster3/mc/plugin/core-bukkit/1.2.2/core-bukkit-1.2.2-dev.jar responded with 200 (Content-Type: application/java-archive)
02:04:14.468 DEBUG | GET /public/cn/hamster3/mc/plugin/core-bukkit/1.2.2/core-bukkit-1.2.2-dev.jar.sha1 from 183.***.***.***
02:04:14.797 DEBUG | HttpRemoteClient | https://maven.airgame.net/maven-airgame/cn/hamster3/mc/plugin/core-bukkit/1.2.2/core-bukkit-1.2.2-dev.jar.sha1 responded with 200 (Content-Type: application/octet-stream)
02:04:14.798 DEBUG | Cannot find 'cn/hamster3/mc/plugin/core-bukkit/1.2.2/core-bukkit-1.2.2-dev.jar.sha1' in 'public' repository, requesting proxied repositories
02:04:14.967 DEBUG | HttpRemoteClient | https://maven.airgame.net/maven-airgame/cn/hamster3/mc/plugin/core-bukkit/1.2.2/core-bukkit-1.2.2-dev.jar.sha1 responded with 200 (Content-Type: application/octet-stream)
02:04:15.013 DEBUG | GET /public/cn/hamster3/mc/plugin/core-bukkit/1.2.2/core-bukkit-1.2.2-dev.jar from 183.***.***.***
02:04:15.014 DEBUG | Gav 'cn/hamster3/mc/plugin/core-bukkit/1.2.2/core-bukkit-1.2.2-dev.jar' found in 'public' repository
```

It seems that the reposilite processed the request correctly, and the error seems to have come from Gradle's build system processing
I really don't have a clue about this. If I provide you with the steps to reproduce, could you help me test it?
You just need to use a new repostilite instance and add it `https://maven.airgame.net/maven-airgame` to the mirrors, and add `compileOnly("cn.hamster3.mc.plugin:core-bukkit:1.2.2")` to your gradle build script dependency. Finally, configure repositories to download dependencies from your repository instance

**Comment by dzikoysk** [comment] 2024-03-09 17:20
As far as I see in logs, Reposilite properly responds with all requested files by Gradle. Client side log:

1. Returns .pom: `Download https://localhost:8080/test/cn/hamster3/mc/plugin/core-bukkit/1.2.2/core-bukkit-1.2.2.pom, took 2 s 60 ms`
2. Returns .module: `Download https://localhost:8080/test/cn/hamster3/mc/plugin/core-bukkit/1.2.2/core-bukkit-1.2.2.module, took 797 ms`
3. Returns requested artifact: `Download https://localhost:8080/test/cn/hamster3/mc/plugin/core-bukkit/1.2.2/core-bukkit-1.2.2-dev.jar, took 2 s 2 ms`

If you want the default one, you can just select this manually:

```kotlin
compileOnly("cn.hamster3.mc.plugin:core-bukkit:1.2.2:")
```

I'm not quite sure how Gradle decides on which classifier should be used by default, but it seems to prefer `dev` over the default one. After taking a look at .module file, I see that the dev files are marked as default apiElements/runtimeElements, so that could be the cause:

```json
"variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-bukkit-1.2.2-dev.jar",
          "url": "core-bukkit-1.2.2-dev.jar",
          "size": 114525,
          "sha512": "aa47dd10891749711e05827396f2c5707da95c9fbb4f350db205a9abf792ea2227cbe19946565f7bedff8815612cd9baf848ff9c5d5cde43eeb608ee624c791e",
          "sha256": "3e5083254813bf22b77d77cbe327783f27d0acc17d4ff6c1d7da327014812368",
          "sha1": "e04b1105a10e1b0e718a657c32f6b7d32d488e31",
          "md5": "6d238138ed2c4d046c696fd71fb8a848"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [ ... ],
      "files": [
        {
          "name": "core-bukkit-1.2.2-dev.jar",
          "url": "core-bukkit-1.2.2-dev.jar",
          "size": 114525,
          "sha512": "aa47dd10891749711e05827396f2c5707da95c9fbb4f350db205a9abf792ea2227cbe19946565f7bedff8815612cd9baf848ff9c5d5cde43eeb608ee624c791e",
          "sha256": "3e5083254813bf22b77d77cbe327783f27d0acc17d4ff6c1d7da327014812368",
          "sha1": "e04b1105a10e1b0e718a657c32f6b7d32d488e31",
          "md5": "6d238138ed2c4d046c696fd71fb8a848"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-bukkit-1.2.2.jar",
          "url": "core-bukkit-1.2.2.jar",
          "size": 8828145,
          "sha512": "1caefaf8a4ae160fea69f5f6cbb9a6f29184c77cb7d2c0a4eaf4eef4cdacde5c3028086573d6d1729f1365cc0f154eb759c0ece7412bc0e76518c11e363e793a",
          "sha256": "e5fbd8501eeeccfb693e79cd0e2d4548e05c7aa7ffa821b55f88006b484f6300",
          "sha1": "6a340e58911d0e249290e938cd9668f66948c5ea",
          "md5": "ec4e09cbee5d35f08201efae69070a31"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-bukkit-1.2.2-sources.jar",
          "url": "core-bukkit-1.2.2-sources.jar",
          "size": 66522,
          "sha512": "00e132aac7f7ba87c1514bdcbf2a69bd93462767cc655e56ed19d7d023ad227af4f5b2159088237022d6eb8505b46bc1bc37b73d1ba1635397daaebdbdf47743",
          "sha256": "2cc11b7bfd256c12c84c31596f1f81cefc81b8887e7f55c44257bc25ade40093",
          "sha1": "0f0e1e2e00e59269b8e437bbe59168b820bf1934",
          "md5": "a3ffab2dffe2db40b00bb1a2baa001fc"
        }
      ]
    }
```

**Comment by MiniDay** [comment] 2024-03-10 02:24
As I said before, I think this is more like a Gradle problem:
When I directly set the repository to my own reposilite address and use `compileOnly("cn.hamster3.mc.plugin:core-bukkit:1.2.2")`, gradle can download the file normally.
When I set the repository to the team's reposilite address, using `compileOnly("cn.hamster3.mc.plugin:core-bukkit:1.2.2")` will download the `-dev` file, and I must use `compileOnly("cn.hamster3.mc. plugin:core-bukkit:1.2.2:")` to download the files I need.
I don't know how Gradle handles dependency downloads, but I checked the `core-bukkit-1.2.2.module` files in the reposilite on both sides and they are exactly the same. Maybe I should submit an issue to gradle?
Anyway, thanks for the help.

**Comment by dzikoysk** [comment] 2024-03-10 12:11
> As I said before, I think this is more like a Gradle problem

Yeah, just wanted to run this on my own to confirm we're not blocking any files. This is still weird that the behavior changes between different repositories tho 🤔  

> Maybe I should submit an issue to gradle?

I think it might be a good idea to at least ask them how they determine which classifier should be used by default. Let me know about the result, if it turns out that we can improve our handling, we can try to address this in a new ticket.

**Closed** 2024-03-10 12:11 UTC
Labels: question
