### ISSUE TITLE
JavaDoc plugin uses old artifact version

### ISSUE THREAD

**Issue by P3ridot** [dzikoysk/reposilite#1519] opened 2022-08-29 18:12 UTC
### What happened?

I have artifact with same version (for eg. 1.0.0), but with snapshots enabled. JavaDoc plugin uses older snapshot instead latest. And there is no way to see JavaDoc for latest snapshot.

### Reposilite version

3.x

**Comment by joshuasing** [comment] 2022-08-30 05:03
I think this bug might have been caused by my changes, I'll have a look into it.
Thanks for the report :)

**Comment by joshuasing** [comment] 2022-08-30 06:57
@P3ridot What URL are you using to access the javadocs?

**Comment by P3ridot** [comment] 2022-09-01 11:30
Same like to dependency, but instead of # I use javadoc. In my case https://repo.titanvale.net/javadoc/snapshots/net/titanvale/titanium-api/1.8.8-R0.1-SNAPSHOT

**Comment by joshuasing** [comment] 2022-09-01 11:41
I only see one version of that dependency in that repository, could you please explain how the Javadoc plugin is using an outdated version? Also if you use `/javadoc/snapshots/<gav>/latest`, it would normally return a snapshot version due to it being a snapshot repository.

If you would prefer me to help you on Discord, please join the Reposilite/"Panda & Projects" server: https://discord.gg/bEMFJfRP

**Comment by joshuasing** [comment] 2022-10-14 10:49
I think I may have found a potential fix for this, I'll make a pull request soon.

**Comment by P3ridot** [comment] 2022-12-04 11:13
Problem is caused by cached javadocs in `javadocs/` directory. It should be removed when artifact version has been changed. I created `cron job` to purge it every day and everything works.

**Comment by joshuasing** [comment] 2022-12-04 11:53
Oh, that would make sense, I didn't think of checking whether it due to the cache.
I will look into versioning the cache somehow so this can be avoided, thanks for the update!

**Closed** 2023-01-30 15:02 UTC
Labels: bug, plugin
