### ISSUE TITLE
Gradle publish fails

### ISSUE THREAD

**Issue by DeadlyMC** [dzikoysk/reposilite#351] opened 2021-02-05 07:09 UTC
I'm trying to deploy some files to a maven repo using the **maven-publish** gradle plugin with no luck. It always errors with a status 401 : Unauthorized.
![Capture](https://user-images.githubusercontent.com/43000902/107000994-db879b80-67ae-11eb-84ec-93205afcb08b.PNG)

This is the gradle publish task:
![image](https://user-images.githubusercontent.com/43000902/107001078-0540c280-67af-11eb-9c45-f0290f749119.png)

The alias and token aren't wrong as ive used them in the web login without any issues.

**Comment by dzikoysk** [comment] 2021-02-05 09:51
Hey :) Did you associate a proper path with `w` permission?

**Comment by DeadlyMC** [comment] 2021-02-05 11:20
yes, m with /*

**Comment by dzikoysk** [comment] 2021-02-05 11:46
Could you enable debug in configuration? As far as I remember, I've added some extra logging during the authorization.

**Comment by DeadlyMC** [comment] 2021-02-05 17:06
![Capture](https://user-images.githubusercontent.com/43000902/107065194-7e1d3a00-6802-11eb-8566-24afef6471ad.PNG)
This is all that shows up when i run `gradlew publish`

**Comment by dzikoysk** [comment] 2021-02-05 18:15
Add `-Dtinylog.writerActive.level=DEBUG` as VM option and check again

**Comment by BluCobalt** [comment] 2021-02-05 19:01
the console output:
![image](https://user-images.githubusercontent.com/37788256/107077197-606bb880-67a1-11eb-9688-16f55554e92b.png)
the gradle exception:
![image](https://user-images.githubusercontent.com/37788256/107077247-6f526b00-67a1-11eb-996b-cc7f2b68ec06.png)

**Comment by dzikoysk** [comment] 2021-02-05 19:45
Nah, I always forget that Gradle does not use basic auth by default 😳 Just add it below the credentials:

```groovy
credentials {
    // [...]
}
authentication {
    basic(BasicAuthentication)
}
```

**Comment by BluCobalt** [comment] 2021-02-05 19:54
Lol, it's fine.
 I added the authentication bit but it still gives me a 401 on `maven-metadata.xml` . Here is my publishing block:
![image](https://user-images.githubusercontent.com/37788256/107082199-af691c00-67a8-11eb-8bee-81b52248d422.png)

**Comment by dzikoysk** [comment] 2021-02-05 20:03
Does your `Authentication` header start with a `Basic` phrase? 

I've added a log statement to print the response message for authentication error during a deploy, check this builds:
[reposilite-2.9.10.zip](https://github.com/dzikoysk/reposilite/files/5934954/reposilite-2.9.10.zip) (GitHub doesn't support .jar files, so rename zip to jar)

**Comment by BluCobalt** [comment] 2021-02-05 20:50
![image](https://user-images.githubusercontent.com/37788256/107087690-ac722980-67b0-11eb-81da-b16419f304ac.png)

**Comment by dzikoysk** [comment] 2021-02-05 22:48
Let's try one more time 🤔 

[reposilite-2.9.10.zip](https://github.com/dzikoysk/reposilite/files/5935704/reposilite-2.9.10.zip)

**Comment by BluCobalt** [comment] 2021-02-05 23:45
![image](https://user-images.githubusercontent.com/37788256/107100408-1e566d00-67c9-11eb-9034-032cf3d34852.png)

**Comment by dzikoysk** [comment] 2021-02-05 23:57
It looks like the associated path does not really match the uri:

![image](https://user-images.githubusercontent.com/4235722/107100929-0822ce00-6816-11eb-885e-c34780394f72.png)

And you have enabled this option in configuration?

```
# Allow to omit name of the main repository in request
# e.g. /org/panda-lang/reposilite will be redirected to /releases/org/panda-lang/reposilite
rewritePathsEnabled: true
```

**Comment by dzikoysk** [comment] 2021-02-06 00:04
> 
> 
> yes, m with /*

Oh, wait, I didn't notice that you have asterisk after slash. Take a look at this table:

![image](https://user-images.githubusercontent.com/4235722/107101251-03124e80-6817-11eb-8d83-13b90f19d4b1.png)

As you can see, there is no path that may end with `*` character. The only place where you can use functional asterisk is at the beginning of the path, to use it as a wildcard for repository name.

**Comment by BluCobalt** [comment] 2021-02-06 01:25
Thank you!  Setting a token with  / worked.

@DeadlyMC you can close this and I'll gen new keys

**Comment by dzikoysk** [comment] 2021-02-06 01:32
I've marked it as a documentation issue and I'll close it when I add `BasicAuthentication` to the docs :) I also think it might be a good idea to add a warning, when someone will generate a token with path that ends with asterisk.

**Comment by BluCobalt** [comment] 2021-02-06 01:32
While you're here, do you know how (if possible) to change the text on the index page? I already set it in the reposilite.cdn but it still just says 
![image](https://user-images.githubusercontent.com/37788256/107104811-2669d900-67d8-11eb-90e9-bfed784d0efd.png)

**Comment by dzikoysk** [comment] 2021-02-06 01:34
Are you sure it is not caused by Cloudflare cache?

**Comment by BluCobalt** [comment] 2021-02-06 02:05
Yes, I have disabled caching for the subdomain with a page rule:
![image](https://user-images.githubusercontent.com/37788256/107105745-b90c7700-67dc-11eb-8f0f-d9303ba61a00.png)

**Comment by dzikoysk** [comment] 2021-02-06 02:12
As I thought, it is a known bug, that you can't use apostrophe:

```
window.REPOSILITE_DESCRIPTION = 'Legacy Fabric's maven repo'
```

You should be able to replace it with `\'` or just the Unicode representation.

**Comment by BluCobalt** [comment] 2021-02-06 02:40
Escaping it worked, thanks!

**Comment by DeadlyMC** [comment] 2021-02-06 06:07
Thank you! I'm able to publish too. Is the basic authentication bit imp? I was able to push without it

**Comment by dzikoysk** [comment] 2021-02-06 09:11
I'm not sure when Gradle uses other auth methods, but there were issues related to this: https://github.com/dzikoysk/reposilite/issues/171#issuecomment-666015137

**Closed** 2021-02-06 19:12 UTC
Labels: documentation
