### ISSUE TITLE
Generated maven-metadata incorrect

### ISSUE THREAD

**Issue by caoli5288** [dzikoysk/reposilite#405] opened 2021-03-17 09:12 UTC
Here is an generated `maven-metadata.xml`

![图片](https://user-images.githubusercontent.com/3120587/111442473-5bf0d300-8743-11eb-85a4-beeece9f9de4.png)

Here are two issues:

1. Snapshot version should not shown in `/metadata/versioning/release` tag.
2. The `/metadata/versioning/versions/version` should ordered asc(current desc).

**Comment by dzikoysk** [comment] 2021-03-17 09:47
The versioning used by your artifact is not a standard snapshot format for Maven specification. Here's the full thread: https://github.com/dzikoysk/reposilite/issues/95#issuecomment-636778268

Did you experience any bug caused by this feature?

**Comment by caoli5288** [comment] 2021-03-18 03:04
@dzikoysk I upload those artifacts by web cli

**Comment by dzikoysk** [comment] 2021-03-25 23:37
Yeah, but it does not change the reported issue. Metadata files may contain extra data to support different features, especially this one, because like I said, snapshot without timestamps are not a part of Maven specification. It has to use `release` tag, because using such an artifact as `snapshot` would cause error. I also didn't find any information about order of versions in the specification, so it looks like it's up to the implementation.

**Comment by caoli5288** [comment] 2021-04-02 03:24
Maybe you're right, but nexus did. Different behaviors will bring confusion to users(At least me).

**Comment by dzikoysk** [comment] 2021-08-15 11:55
Addressed by #550

**Closed by dzikoysk** 2021-08-15 11:55 UTC
Labels: cosmetic
