### ISSUE TITLE
Adding delete  artifact functionality to the UI

### ISSUE THREAD

**Issue by qlanduril** [dzikoysk/reposilite#1373] opened 2022-06-06 09:25 UTC
### Request details

As Dzikoysk mentioned in discord server there is no such possibility. One needs to mount and delete the artifact manually.

[Mentioned discord dialogue](https://discord.com/channels/204728244434501632/875148821842231296/972182996310437888)

**Comment by dzikoysk** [comment] 2022-06-08 15:26
It's a duplicate of #1303, but I'll rename the origin issue to make it more explicit about the requested feature

**Closed** 2022-06-08 15:26 UTC
Labels: duplicate
